### ISSUE TITLE
short name binaries incomplete

### ISSUE THREAD

**Issue by pohmelie** [andrewwutw/build-djgpp#10]
It looks like short name binaries missed some of long name ones. `size` for example, 
we have `bin/i586-pc-msdosdjgpp-size`, but have no `i586-pc-msdosdjgpp/bin/size`. So, I think it is better to link/copy them from long to short.

**Comment by andrewwutw** [comment]
Fix in 5df9038f0dcbeb16b51fce2cef7edaa01b80d36a

**Comment by andrewwutw** [comment]
Fix in 5df9038f0dcbeb16b51fce2cef7edaa01b80d36a . :smile: 
Now copied short name binaries : gcc g++ c++ addr2line c++filt cpp size strings .

**Comment by pohmelie** [comment]
Great! Thanks for awesome project!
