### ISSUE TITLE
Support for compilation under FreeBSD

### ISSUE THREAD

**Issue by ardovm** [andrewwutw/build-djgpp#11]
The current trunk version of build-djgpp does not allow to build GCC 4.8.5 under FreeBSD 9-stable.
[This patch](https://github.com/andrewwutw/build-djgpp/files/85873/freebsd-4.8.5.patch.txt) seems to make it possible.
I am submitting it here so that you can review it and integrate it, if you wish.

The patch brings the following changes:

* use `gmake` instead of `make` (that is: GNU Make instead of BSD Make);
* use the standard Clang compiler instead of the standard GCC  (by "standard" I mean that they are both available in the base distribution of FreeBSD);
* remove the `--verbose` option from the `patch` invocations inside `unpack-gcc.sh` (BSD Patch does not support that option).

All the above only happens on FreeBSD systems (identified by the `uname` command).

I am not sure whether there are any ``cleaner'' ways to fix the problems. I can only tell that I could successfully build gcc 4.8.5 after applying that patch on my system:

    $ uname
    FreeBSD myhost 9.3-STABLE FreeBSD 9.3-STABLE #140 r293654M: Mon Jan 11 09:55:00 CET 2016     root@myhost:/usr/obj/usr/src/sys/GENERIC  i386

If you wish, I can prepare similar patches for the other scripts in the `script` directory. Before starting, I would like to hear if you have any remarks about this patch (code style etc).
I am of course open to your suggestions on this topic.

**Comment by andrewwutw** [comment]
Ok, I integrated your patch to all versions in script/ directory in my latest commit, with some other minor modifications. I tested on FreeBSD 10.2-STABLE (Vagrant VM) and no problem.
