### ISSUE TITLE
DXE3 not included

### ISSUE THREAD

**Issue by maraakate** [andrewwutw/build-djgpp#14]
Hi, thank you for these win32 cross-compilers.  Makes it a lot easier to compile large projects, especially with new version of make.exe from MSYS to allow parallel building.

Your versions posted do not include DXE3.  During compile it fails to find _dlsymresolver.

Thanks for your builds, and I look forward to using them full time on windows if this issue can be resolved.

**Comment by maraakate** [comment]
I forgot to mention this is for the DJGPP GCC 4.84 no mingw required build that you provide.

I did a quick compare of DXE.H from the include/sys and it appears your version is from 2003.  Are these builds DJGPP v2.03?  If they are, can you update them to v2.05?  2.05 has been out for about a year now and has serious fixes for DXE memory leaks.

**Comment by maraakate** [comment]
5.10 is updated to 2.05 I have noticed, but it still is missing dxe3gen to make DXE files.

**Comment by andrewwutw** [comment]
@maraakate Ok, I have a test version which provides DXE tools (for MinGW). It is in release page : 

https://github.com/andrewwutw/build-djgpp/releases/tag/v2.2-dxe

**Comment by maraakate** [comment]
Thanks.  Currently we are using GCC4 and GCC5 for our projects so I just copied the dxe*.exe files and it appeared to generate a DXE with no problems.  I'm on the road, so I will be unable to test it further until Thursday.  I'll let you know how it worked out for me.

**Comment by maraakate** [comment]
OK.  I tested running our program in dosbox with the dxe3gen you supplied and it seems to work properly.  I will test on real hardware Thursday, but I'm fairly confident that it should work.  Thank you for looking into the issue.   Definitely a lot easier than having to get into VirtualBox and FTP'ing the files to my other computer every time I need to do a compile.

**Comment by maraakate** [comment]
Awesome, tested it on real hardware and works as it should.  Thank you so much.

**Comment by maraakate** [comment]
One more thing.  Recently we ran into an issue that DXE3Gen is not generating extended relocations properly.  There is a patch, it is being sent upstream to CVS in a couple of days.

Can you apply the following patch to the source and upload a new dxe3gen for me to test?
[dxe3gen-test2.zip](https://github.com/andrewwutw/build-djgpp/files/965591/dxe3gen-test2.zip)

See https://groups.google.com/forum/#!topic/comp.os.msdos.djgpp/VOyJcUMYqOE for more information.

Thanks!
Frank

**Comment by andrewwutw** [comment]
@maraakate Ok, I uploaded GCC 6.3.0 / 5.4.0 / 4.9.4 with DXE and DXE3GEN patch for MinGW.

https://github.com/andrewwutw/build-djgpp/releases/tag/v2.4

**Comment by maraakate** [comment]
Works great, but you forgot to update dxe.ld in djgpp\i586-pc-msdosdjgpp\lib

Here is the updated version:

`OUTPUT_FORMAT("coff-go32")

FORCE_COMMON_ALLOCATION

SECTIONS {
  .text : {
    *(.text)
    *(.text.*)
    *(.gnu.linkonce.t*)
    *(.const*)
    *(.ro*)
    *(.gnu.linkonce.r*)
    djgpp_first_ctor = . ;
    *(SORT(.ctors.*))
    *(.ctor)
    *(.ctors)
    djgpp_last_ctor = . ;
    djgpp_first_dtor = . ;
    *(SORT(.dtors.*))
    *(.dtor)
    *(.dtors)
    djgpp_last_dtor = . ;
    *(.data)
    *(.data.*)
    *(.gcc_exc*)
    ___EH_FRAME_BEGIN__ = . ;
    *(.eh_fram*)
    ___EH_FRAME_END__ = . ;
    LONG(0);
    *(.gnu.linkonce.d*)
    *(.bss .bss.* .gnu.linkonce.b.*)
    *(COMMON)
  }
  /DISCARD/ : { *(gnu.lto_*) }
}
`
By the end of next week these changes should be commited to DJGPP CVS.  I don't know if you're building from that or not.  But these changes are necessary for DXEs to work with larger, more complex projects.

**Comment by andrewwutw** [comment]
@maraakate Ok, I uploaded a new version with updated dxe.ld

https://github.com/andrewwutw/build-djgpp/releases/tag/v2.5
