### ISSUE TITLE
Add script for gcc 7.1.0

### ISSUE THREAD

**Issue by jwt27** [andrewwutw/build-djgpp#15]
It's finally here! :)

**Comment by andrewwutw** [comment]
@jwt27 But there is no djcross-gcc for GCC 7.1.0 yet. :(

http://www.delorie.com/pub/djgpp/rpms/

I have to wait somebody to port djcross-gcc for GCC 7.1.0, then I can port it to cross-compile on Linux/Win32 etc.

**Comment by jwt27** [comment]
I just tried compiling gcc 7 myself just to see what would happen.  
And... it just works? That was quite unexpected. I didn't do anything special, just `../configure --target=i586-pc-msdosdjgpp --prefix=/usr/local/djgpp` basically.
The previous gcc 6 (with the djgpp runtime libc, etc) was still installed in `/usr/local/djgpp` so that may have helped. Still I'm curious now, what is the djcross package supposed to do exactly?

Also I used a script in the gcc source tree (`./contrib/download_prerequisites`) that installs the various libraries used by gcc (gmp, mpfr, mpc, isl). Maybe you could use that in your build scripts too, so you don't have to download and compile them separately.

**Comment by andrewwutw** [comment]
@jwt27 Ok, uploaded : 

https://github.com/andrewwutw/build-djgpp/releases/tag/v2.6
