### ISSUE TITLE
pthreads support

### ISSUE THREAD

**Issue by user1095108** [andrewwutw/build-djgpp#19]
AFAIK your builds don't support threads, but there is a library called GNU pth that supports DOS (don't bother with FSU Pthreads, it's too old of an implementation, even though you can make it to compile). I'd like to see a build with pthreads support, so that std::thread would work.

**Comment by andrewwutw** [comment]
@user1095108 Sorry, but this project is just for porting the official DJGPP (which only runs under DOS) to other Unix-like platforms. So, If something is not included in the official DJGPP,  this project won't include it neither. 😓

**Comment by user1095108** [comment]
There are 2 pthreads ports in the official repository and thread support is
a part of glibc and stdc++.

**Comment by lpsantil** [comment]
djgpp does not produce binaries that use glibc [0].  It uses something custom which often a source of confusion [1][2].

[0] http://www.delorie.com/pub/djgpp/current/v2/djlsr205.zip
[1] http://www.delorie.com/djgpp/v2faq/faq19_1.html
[2] http://www.delorie.com/djgpp/v2faq/faq19_2.html

**Comment by user1095108** [comment]
It does include the libstdc++ .
