### ISSUE TITLE
Building 4.7.3 doesn't work with current makeinfo

### ISSUE THREAD

**Issue by GitMensch** [andrewwutw/build-djgpp#22]
the following lines need to be changed that current `makeinfo` can process the file - otherwise the build will not finish (make returned error 1):

```diff
-@tab General: @tex press@@gnu.org @end tex
+@tab General:
+@tex press@@gnu.org
+@end tex
 @item Free Software Foundation
-@tab Orders:  @tex sales@@gnu.org @end tex
+@tab Orders:
+@tex sales@@gnu.org
+@end tex
```

Notes:

* this likely applies to the some of the more current versions, too (just checked 7.2.0 and it doesn't occurs there)
* the texinfo sources still generate a bunch of warnings (but no further errors)
* the changes should be integrated in the patch applied to gcc sources
* older versions of `makeinfo` should work with this, too - but I didn't checked
* normally `makeinfo` shouldn't be called at all as the generated info files are normally part of the release tarballs - it is therefore likely a good idea to check this and try if running `touch` on it on the correct part of the build fixes the invocation completely

**Comment by GitMensch** [comment]
Hm, as the patch isn't invoking `sed` but uses `patch` - are you sure that these parts are 100% identical in all GCC 4.x versions?

**Comment by andrewwutw** [comment]
@GitMensch Yes, I tried to use ```sed``` to modify gcc.texi but I don't know how to add new line character in the replacement string  :confused: ... So I use ```patch```.

I tested all versions supported in script/ directory, only 4.7.3, 4.8.4, 4.8.5 need this patch. gcc.texi file of other versions is ok.

**Comment by GitMensch** [comment]
> I tried to use `sed` to modify gcc.texi but I don't know how to add new line character in the replacement string :confused: ...

Maybe this gives a useful hint:

```sh
/tmp$ echo test@stuff
test@stuff
/tmp$ echo test@stuff | sed 's/\(@stuff\)/\n\1/g'
test
@stuff
```

**Comment by andrewwutw** [comment]
@GitMensch Ok, I figured out the problem, OSX built-in sed doesn't support ```\n``` for new line, I have to use GNU sed instead. It is in commit de7fc54 . 😃
