### ISSUE TITLE
Support for GCC 8.1.0 and Binutils 2.30

### ISSUE THREAD

**Issue by noir631** [andrewwutw/build-djgpp#29]

**Comment by jwt27** [comment]
@andrewwutw hasn't updated this repository in a while. I hope he's okay.
I try to keep my fork up to date, over here: https://github.com/jwt27/build-gcc. Support for gcc 8.2 and binutils 2.31.1 was added recently.

**Comment by saffron151** [comment]
@jwt27 Yeah, I made a custom script for these versions. It compiles successfully, (with some warnings)

**Comment by andrewwutw** [comment]
v3.0 Supports GCC 8.3.0 and Binutils 2.30.
