### ISSUE TITLE
bnu229s.zip 404 Not Found

### ISSUE THREAD

**Issue by BenCollver** [andrewwutw/build-djgpp#31]
When i run the build script, it fails to download the DJGPP sources.

```
$ DJGPP_PREFIX=/home/ben/local/cross-djgpp ./build-djgpp.sh 7.2.0
Building version : 7.2.0
Download source files...
Download http://www.delorie.com/pub/djgpp/deleted/v2gnu/bnu229s.zip ...
Command : curl -f http://www.delorie.com/pub/djgpp/deleted/v2gnu/bnu229s.zip -L -o bnu229s.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
rm: cannot remove 'bnu229s.zip': No such file or directory
Download http://www.delorie.com/pub/djgpp/deleted/v2gnu/bnu229s.zip failed.
```

FYI, i can still find that file on the DJGPP FTP site.

`ftp://ftp.delorie.com/pub/djgpp/deleted/v2gnu/bnu229s.zip`

Any suggestions?  Thanks!

**Comment by hadrosoft** [comment]
I ran into that problem too, but then I found that the download location can be configured:

In the `script` directory, open up the script file `7.2.0` (or whatever version you wish to install). There will be two lines near the top that read:

```
#DJGPP_DOWNLOAD_BASE="ftp://ftp.delorie.com/pub"
DJGPP_DOWNLOAD_BASE="http://www.delorie.com/pub"
```

Un-comment the first one and comment the first one. Save, run the install script again, and you should be good to go!

**Comment by BenCollver** [comment]
Thanks, that works for me!
