### ISSUE TITLE
http download from www.delorie.com is gone

### ISSUE THREAD

**Issue by SuperIlu** [andrewwutw/build-djgpp#32]
seems like the number of mirrors is dwindling :(

**Comment by hoeppie** [comment]
Hi,
changed in script (example 7.2.0) the mirror..
#DJGPP_DOWNLOAD_BASE="ftp://ftp.delorie.com/pub"
#DJGPP_DOWNLOAD_BASE="http://www.delorie.com/pub"
DJGPP_DOWNLOAD_BASE="ftp://ftp.fu-berlin.de/pc/languages"
 I hope they will stay..

**Comment by andrewwutw** [comment]
v3.0 downloads files from www.mirrorservice.org .
