### ISSUE TITLE
Add support for DJGPP 2.0.5 and gcc 5.1.0

### ISSUE THREAD

**Issue by lpsantil** [andrewwutw/build-djgpp#4]
Please add support for DJGPP 2.0.5 and gcc 5.1.0.

**Comment by andrewwutw** [comment]
Ok, I will support them when I have time... :open_mouth:

**Comment by lpsantil** [comment]
Awesome!  Thanks for all your hard work.  By the way, I used build-djgpp to [port lz4 to djgpp][0], in case you or your customers might be interested.

[0]: https://github.com/Cyan4973/lz4/pull/113

**Comment by andrewwutw** [comment]
DJGPP 5.2.0 is supported now. :smile:

**Comment by lpsantil** [comment]
Thanks!!!
