### ISSUE TITLE
Installation of prebuilt binaries?

### ISSUE THREAD

**Issue by cblc** [andrewwutw/build-djgpp#48]
The readme says that the standard build assumes the installation will be performed on `/usr/local/djgpp`. It also mentions the `DJGPP_PREFIX` variable, but it's not clear if that variable is used only at build time, or if the prebuilt binaries also honor it.

What I really want to know is if I can just take a prebuilt release, unzip it in any directory of my choice, and run it from there. If affirmative, should I set any env variables?

Thanks!!

**Comment by lpsantil** [comment]
When you build gcc, you need to tell it where it will expect to find its crt0, headers, etc.  The prebuilt binaries expect `/usr/local/djgpp` unless told otherwise.  The README shows you how to tell it otherwise:

https://github.com/andrewwutw/build-djgpp#using-djgpp-compiler

**Comment by cblc** [comment]
Ok, thank you. The variable to be set is GCC_EXEC_PREFIX then.
