### ISSUE TITLE
djcrx no longer available at script locations

### ISSUE THREAD

**Issue by lpsantil** [andrewwutw/build-djgpp#5]
djcrx is no longer available at Andris Pavenis' site, http://ap1.pp.fi/djgpp/djdev/djgpp/20140421/.

**Comment by zelurker** [comment]
Same thing for djlsr204.zip.
Both can be found using google, the original site is there :
ftp://ftp.delorie.com/pub/djgpp/beta/v2/

**Comment by andrewwutw** [comment]
Thanks. Updated to new download location. :smile:
